const bookCategory=[
    { id: 1, label: "Literatura romana", value: "literatura_romana" },
    { id: 2, label: "Carti politiste", value: "carti_politiste" },
    { id: 3, label: "Carti de dragoste", value: "carti_de_dragoste" },
    { id: 4, label: "Best seller", value: "best_seller" },
    { id: 5, label: "Fantasy", value: "fantasy" },
    { id: 6, label: "Biografii si Memorialistica", value: "biografii_memorialistica" },
    { id: 7, label: "Literatura straina", value: "literatura_straina" },
    { id: 8, label: "Science fiction", value: "science_fiction" },
    { id: 9, label: "Horror", value: "horror" },
    { id: 10, label: "Poezie", value: "poezie" },
    { id: 11, label: "Bibliofilie", value: "bibliofilie" },
    { id: 12, label: "Carti cu autograf", value: "carti_cu_autograf" },
    { id: 13, label: "Filozofie", value: "filozofie" },
    { id: 14, label: "Critica/Studii", value: "critica_studii" },
    { id: 15, label: "Critica literara", value: "critica_literara" },
    { id: 16, label: "Eseuri", value: "eseuri" },
    { id: 17, label: "istorie_literara", value: "istorie_literara" },
    { id: 18, label: "Psihologie", value: "psihologie" },
    { id: 19, label: "Dezvoltare personala", value: "dezvoltare_personala" },
    { id: 20, label: "Istorie", value: "istorie" },
    { id: 21, label: "Etnografie", value: "etnografie" },
    { id: 22, label: "Politica", value: "politica" },
    { id: 23, label: "Arta", value: "arta" },
    { id: 24, label: "Pictura", value: "pictura" },
    { id: 25, label: "Muzica", value: "muzica" },
    { id: 26, label: "Istoria artei", value: "istoria_artei" },
    { id: 27, label: "Fotografie", value: "fotografie" },
    { id: 28, label: "Cinematografie", value: "cinematografie" },
    { id: 29, label: "Sculptura", value: "sculptura" },
    { id: 30, label: "Alte arte", value: "alte_arte" },
    { id: 31, label: "Arhitectura", value: "arhitectura" },
    { id: 32, label: "Carti scolare", value: "carti_scolare" },
    { id: 33, label: "Povesti, Povestiri", value: "povesti_povestiri" },
    { id: 34, label: "Literatura pentru copii", value: "literatura_pentru_copii" },
    { id: 35, label: "Dictionare", value: "dictionare" },
    { id: 36, label: "Dictionare de specialitate", value: "dictionare_de_specialitate" },
    { id: 37, label: "Dictionare ale limbii romane", value: "dictionare_ale_limbii_romane" },
    { id: 38, label: "Dictionare bilingve", value: "dictionare_bilingve" },
    { id: 39, label: "Dictionare straine", value: "dictionare_straine" },
    { id: 40, label: "Cultura", value: "cultura" },
    { id: 41, label: "Enciclopedii", value: "enciclopedii" },
    { id: 42, label: "Atlase", value: "atlase" },
    { id: 43, label: "Albume", value: "albume" },
    { id: 44, label: "Teatru", value: "teatru" },
    { id: 45, label: "Monografii", value: "monografii" },
    { id: 46, label: "Educatie", value: "educatie" },
    { id: 47, label: "Cultura generala", value: "cultura_generala" },
    { id: 48, label: "Cursuri limbi straine", value: "cursuri_limbi_straine" },
    { id: 49, label: "Lingvistica", value: "lingvistica" },
    { id: 50, label: "Hobby", value: "hobby" },
    { id: 51, label: "Lucru manual", value: "lucru_manual" },
    { id: 52, label: "Arte martiale", value: "arte_martiale" },
    { id: 53, label: "Colectionabile", value: "colectionabile" },
    { id: 54, label: "Jocuri", value: "jocuri" },
    { id: 55, label: "Trenuri si vehicule", value: "trenuri_si_vehicule" },
    { id: 56, label: "Vanatoare si pescuit", value: "vanatoare_si_pescuit" },
    { id: 57, label: "Amenajari/Gradinarit", value: "amenajari_gradinarit" },
    { id: 58, label: "Sport", value: "sport" },
    { id: 59, label: "Gastronomie", value: "gastronomie" },
    { id: 60, label: "Sah", value: "sah" },
    { id: 61, label: "Filatelie", value: "filatelie" },
    { id: 62, label: "Animale de companie", value: "animale_de_companie" },
    { id: 63, label: "Avioane", value: "avioane" },
    { id: 64, label: "Literatura clasica", value: "literatura_clasica" },
]

export default bookCategory;